# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/zynq_pro/LAB6_8bit/LAB6_8bit/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3.xci
# IP: The module: 'weight_ram_rd3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zynq_pro/LAB6_8bit/LAB6_8bit/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_ram_rd3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/zynq_pro/LAB6_8bit/LAB6_8bit/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3.xci
# IP: The module: 'weight_ram_rd3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zynq_pro/LAB6_8bit/LAB6_8bit/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_ram_rd3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
