# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/modeltech64_2020.4/win64
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.cache/wt [current_project]
set_property parent.project_path Y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc2.0.bias.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc1.0.bias.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc3.bias.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/input_data/sel_data_128.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc2.0.weight32.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc3.weight4.coe
add_files y:/Code/github/ASIC-PYNQ/LAB5/parameter/fc1.0.weight_128.coe
read_verilog -library xil_defaultlib {
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/adder_tree.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/adder_tree2.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/adder_tree3.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/fc.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/fc_2.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/fc_3.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/mult_array24.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/multi_array.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/multi_array32.v
  Y:/Code/github/ASIC-PYNQ/LAB5/rtl/top.v
}
read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_rd3/bias_ram_rd3.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_rd3/bias_ram_rd3_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_weight_fc3/bias_weight_fc3.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_weight_fc3/bias_weight_fc3_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/input_ram_rd3/input_ram_rd3.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/input_ram_rd3/input_ram_rd3_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_16/mult_16.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_16/mult_16_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_rd3/weight_ram_rd3_ooc.xdc]

read_ip -quiet y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc3/weight_ram_fc3.xci
set_property used_in_implementation false [get_files -all y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc3/weight_ram_fc3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fc_top_ip -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fc_top_ip.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fc_top_ip_utilization_synth.rpt -pb fc_top_ip_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
