# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8.xci
# IP: The module: 'mult_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8.xci
# IP: The module: 'mult_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/mult_8/mult_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
