# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/Code/github/ASIC-PYNQ/LAB6/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24.xci
# IP: The module: 'multi_24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB6/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_24'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Y:/Code/github/ASIC-PYNQ/LAB6/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24.xci
# IP: The module: 'multi_24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB6/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/multi_24/multi_24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
