# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/weight_ram_rd3/weight_ram_rd3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_ram_rd3 || ORIG_REF_NAME==weight_ram_rd3} -quiet] -quiet

# IP: ip/input_ram_rd3/input_ram_rd3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_ram_rd3 || ORIG_REF_NAME==input_ram_rd3} -quiet] -quiet
