# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xci
# IP: The module: 'async_outfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xci
# IP: The module: 'async_outfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/ip/async_outfifo/async_outfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_outfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
