# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/ASIC-PYNQ/LAB4/prj/project_1.srcs/sources_1/ip/bias_ram_rd3/bias_ram_rd3.xci
# IP: The module: 'bias_ram_rd3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/LAB4/prj/project_1.gen/sources_1/ip/bias_ram_rd3/bias_ram_rd3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ram_rd3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/GitHub/ASIC-PYNQ/LAB4/prj/project_1.srcs/sources_1/ip/bias_ram_rd3/bias_ram_rd3.xci
# IP: The module: 'bias_ram_rd3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/LAB4/prj/project_1.gen/sources_1/ip/bias_ram_rd3/bias_ram_rd3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ram_rd3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
