# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/design_1_pl_top_fc_0_0.xci
# IP: The module: 'design_1_pl_top_fc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_rd3/weight_ram_rd3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_rd3 || ORIG_REF_NAME==weight_ram_rd3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc3/weight_ram_fc3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_fc3 || ORIG_REF_NAME==weight_ram_fc3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc2/weight_ram_fc2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_fc2 || ORIG_REF_NAME==weight_ram_fc2} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/mult_8/mult_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_8 || ORIG_REF_NAME==mult_8} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_weight_fc3/bias_weight_fc3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_weight_fc3 || ORIG_REF_NAME==bias_weight_fc3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_rd3/bias_ram_rd3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ram_rd3 || ORIG_REF_NAME==bias_ram_rd3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_fc2/bias_ram_fc2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ram_fc2 || ORIG_REF_NAME==bias_ram_fc2} -quiet] -quiet

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_rd3/weight_ram_rd3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc3/weight_ram_fc3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc2/weight_ram_fc2_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_weight_fc3/bias_weight_fc3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_rd3/bias_ram_rd3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_fc2/bias_ram_fc2_ooc.xdc

# IP: E:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/design_1_pl_top_fc_0_0.xci
# IP: The module: 'design_1_pl_top_fc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_rd3/weight_ram_rd3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_rd3 || ORIG_REF_NAME==weight_ram_rd3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc3/weight_ram_fc3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_fc3 || ORIG_REF_NAME==weight_ram_fc3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc2/weight_ram_fc2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weight_ram_fc2 || ORIG_REF_NAME==weight_ram_fc2} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/mult_8/mult_8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_8 || ORIG_REF_NAME==mult_8} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_weight_fc3/bias_weight_fc3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_weight_fc3 || ORIG_REF_NAME==bias_weight_fc3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_rd3/bias_ram_rd3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ram_rd3 || ORIG_REF_NAME==bias_ram_rd3} -quiet] -quiet

# IP: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_fc2/bias_ram_fc2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ram_fc2 || ORIG_REF_NAME==bias_ram_fc2} -quiet] -quiet

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_rd3/weight_ram_rd3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc3/weight_ram_fc3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/weight_ram_fc2/weight_ram_fc2_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_weight_fc3/bias_weight_fc3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_rd3/bias_ram_rd3_ooc.xdc

# XDC: e:/asic/prj/LAB5_2019/LAB5_2019.srcs/sources_1/bd/design_1/ip/design_1_pl_top_fc_0_0/src/bias_ram_fc2/bias_ram_fc2_ooc.xdc
