# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.srcs/sources_1/bd/design_1/ip/design_1_pl_top_0_0/design_1_pl_top_0_0.xci
# IP: The module: 'design_1_pl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] -quiet

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/xdc/pynqz2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pl_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.srcs/sources_1/bd/design_1/ip/design_1_pl_top_0_0/design_1_pl_top_0_0.xci
# IP: The module: 'design_1_pl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] -quiet

# IP: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_infifo/async_infifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_infifo || ORIG_REF_NAME==async_infifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/prj/ASIC-PYNQ.srcs/sources_1/ip/async_outfifo/async_outfifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==async_outfifo || ORIG_REF_NAME==async_outfifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/GitHub/ASIC-PYNQ/LAB1/prj/ASIC-PYNQ.gen/sources_1/bd/design_1/ip/design_1_pl_top_0_0/xdc/pynqz2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pl_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
