# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/GitHub/ASIC-PYNQ/lab8/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2.xci
# IP: The module: 'bias_ram_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/lab8/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ram_fc2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/GitHub/ASIC-PYNQ/lab8/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2.xci
# IP: The module: 'bias_ram_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/ASIC-PYNQ/lab8/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/bias_ram_fc2/bias_ram_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ram_fc2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
