# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2.xci
# IP: The module: 'weight_ram_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_ram_fc2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2.xci
# IP: The module: 'weight_ram_fc2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/github/ASIC-PYNQ/LAB5/prj/LAB5_2019/LAB5_2019.srcs/sources_1/ip/weight_ram_fc2/weight_ram_fc2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weight_ram_fc2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
